apiVersion: v1
kind: Endpoints
metadata:
  name: kyverno-shadow-metrics
  namespace: monitoring
subsets:
  - addresses:
      - ip: {{ .Values.monitoring.kyvernoPodIP }}
    ports:
      - name: metrics
        port: 8000
